shared:
  pretrained_clip: "openai/clip-vit-large-patch14"
  noise_scale: 0.2

generator:
  device: "cuda"
  max_grid_width: null # null로 설정되면 고정된 사이즈의 그리드맵을 생성
  annotation_batch_size: 512
  dataset: "refcoco"
  splitby: "unc"
  split: "train"

test:
  maskclip:
    text_noise_scale: ${shared.noise_scale}
    num_text_augmentations: 1


model:
  vision_model:
    _target_: "model.base.clip_model.CLIPVisionModel"
    pretrained_name: ${shared.pretrained_clip}

  text_model:
    _target_: "model.base.clip_model.CLIPTextModel"
    pretrained_name: ${shared.pretrained_clip}
